# 基础镜像
FROM nginx
# author
MAINTAINER ms

# 挂载目录
VOLUME /home/ms/projects/ms-ui
# 创建目录
RUN mkdir -p /home/ms/projects/ms-ui
# 指定路径
WORKDIR /home/ms/projects/ms-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
RUN chown -R nginx:nginx /home/ms/projects/ms-ui
# 复制html文件到路径
#COPY ./html/dist /home/ms/projects/ms-ui
