pipeline {
    agent any

    parameters {
        gitParameter branch: '', branchFilter: '.*', defaultValue: 'master', description: '分支', name: 'branch', quickFilterEnabled: false, selectedValue: 'NONE', sortMode: 'NONE', tagFilter: '*', type: 'GitParameterDefinition'
        string defaultValue: 'git@github.com:oyh980707/JavaArchitects.git', description: 'git地址', name: 'srcUrl'
        choice(name: '服务', choices: ['mysql', 'redis', 'nacos'], description: '中间件服务')
        credentials credentialType: 'com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey', defaultValue: '51ec1f69-74c0-4f01-87bf-8a29eb2ad814', description: '凭证', name: 'Credential', required: true
    }

    stages {
        stage('拉取代码') {
            steps {
                deleteDir()
                println("${params.branch}")
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: "${params.branch}"]],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    submoduleCfg: [],
                    userRemoteConfigs: [[credentialsId: "${params.Credential}", url: "${params.srcUrl}"]]])
            }
        }
        stage('启动基础服务') {
             steps {
                 sh 'pwd'
             }
         }
    }

}